
include: "rules/static_env.smk"
include: "rules/functions.smk"
include: "rules/dynamic_env.smk"
include: "rules/utils.smk"
include: "rules/loading.smk"
include: "rules/transforming.smk"
include: "rules/packaging.smk"


rule build_reference_container:
    input:
        collect_base_images,
        collect_reference_container_build_targets
