
metadata_ncbi-t2t-chm13hg002:
  name: ncbi-t2t-chm13hg002
  version: 0
  author: Peter.Ebert
  contact: peter.ebert@iscb.org
  base_image: base_v0
  labels:
  - "homo sapiens"
  - "chm13"
  - "reference genome"
  - "T2Tv1.1"
  - "chm13_1-22XMT"
  - "hg002_XY"
  - "no chr prefix"
  - "GCA_009914755.3"
  - "GCA_020881995.1_ASM2088199v1"
  sources:
  -
    provider: ftp
    prefix: ftp.ncbi.nlm.nih.gov/genomes/all/GCA/009/914/755/GCA_009914755.3_CHM13_T2T_v1.1
    files:
    -
      - GCA_009914755.3_CHM13_T2T_v1.1.fasta
      - genome.fasta
      - t2tv11_chm13.fasta
      - decompress: GCA_009914755.3_CHM13_T2T_v1.1_genomic.fna.gz
    -
      - GCA_009914755.3_CHM13_T2T_v1.1.dict
      - genome.dict
      - t2tv11_chm13.dict
      - derive:
          input: GCA_009914755.3_CHM13_T2T_v1.1.fasta
          singularity: https://depot.galaxyproject.org/singularity/samtools:1.6--hb116620_7
          shell: samtools dict {input} > {output}
    -
      - GCA_009914755.3_CHM13_T2T_v1.1.fasta.fai
      - genome.fasta.fai
      - t2tv11_chm13.fasta.fai
      - derive:
          input: GCA_009914755.3_CHM13_T2T_v1.1.fasta
          singularity: https://depot.galaxyproject.org/singularity/samtools:1.6--hb116620_7
          shell: samtools faidx {input}
    -
      - GCA_009914755.3_CHM13_T2T_v1.1.assembly-report.txt
      - t2tv11_chm13.assembly-report.txt
      - rename: GCA_009914755.3_CHM13_T2T_v1.1_assembly_report.txt
    -
      - GCA_009914755.3_CHM13_T2T_v1.1.assembly-stats.txt
      - t2tv11_chm13.assembly-stats.txt
      - rename: GCA_009914755.3_CHM13_T2T_v1.1_assembly_stats.txt
    -
      - GCA_009914755.3_CHM13_T2T_v1.1.primary-chr2acc.tsv
      - t2tv11_chm13.primary-chr2acc.tsv
      - rename: GCA_009914755.3_CHM13_T2T_v1.1_assembly_structure/Primary_Assembly/assembled_chromosomes/chr2acc
    -
      - GCA_009914755.3_CHM13_T2T_v1.1.mito-chr2acc.tsv
      - t2tv11_chm13.mito-chr2acc.tsv
      - rename: GCA_009914755.3_CHM13_T2T_v1.1_assembly_structure/non-nuclear/assembled_chromosomes/chr2acc
  -
    provider: ftp
    prefix: ftp.ncbi.nlm.nih.gov/genomes/all/GCA/020/881/995/GCA_020881995.1_ASM2088199v1
    files:
    -
      - GCA_020881995.1_ASM2088199v1.fasta
      - t2t_hg002_XY.fasta
      - decompress: GCA_020881995.1_ASM2088199v1_genomic.fna.gz
    -
      - GCA_020881995.1_ASM2088199v1.assembly-report.txt
      - t2t_hg002_XY.assembly-report.txt
      - rename: GCA_020881995.1_ASM2088199v1_assembly_report.txt
    -
      - GCA_020881995.1_ASM2088199v1.assembly-stats.txt
      - t2t_hg002_XY.assembly-stats.txt
      - rename: GCA_020881995.1_ASM2088199v1_assembly_stats.txt
